name: Build and Publish

on:
  push: 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
      id-token: write
      pages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build
      if: github.event_name != 'pull_request'
      run: |
        bash make.sh build
      
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'site'

    - name: Deploy to GitHub Pages
      if: github.event_name != 'pull_request'  
      id: deployment
      uses: actions/deploy-pages@v4
      
 
 